/**
  * @file stspin220.c
  * @author generated by mrt-device utility 
  * @link [https://github.com/uprev-mrt/mrtutils/wiki/mrt-device]
  * @brief Device driver for STSPIN220 device
  *
  */

#include "stspin220.h"



/**
 * @brief initializes device
 * @param dev ptr to STSPIN220 device
 * @return status 
 */
static mrt_status_t spn_init(stspin220_t* dev)
{   
    /* Initialize Register Descriptors */


    /*user-block-init-start*/
    /*user-block-init-end*/

    return MRT_STATUS_OK;
}



mrt_status_t spn_test(stspin220_t* dev)
{
    mrt_status_t status = MRT_STATUS_ERROR;
    /*user-block-test-start*/

    /*user-block-test-end*/
    return status;
}


/*user-block-bottom-start*/
/*user-block-bottom-end*/
